services:
  web:
    image: kobums/tomelater_web:${VERSION:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - BUILDKIT_INLINE_CACHE=1
      shm_size: '2gb'
    container_name: tomelater_web
    ports:
      - '9006:9006'
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    environment:
      - NODE_ENV=production